"""initial schema

Revision ID: 8c0076e38b48
Revises:
Create Date: 2026-08-22 03:03:51.215885
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8c0076e38b48"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """스키마를 최신 리비전으로 올린다."""
    # 한글 부분일치 검색 GIN 인덱스의 연산자 클래스를 제공한다.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "keywords",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.Enum("include", "exclude", name="keyword_kind"), nullable=False),
        sa.Column(
            "match_mode", sa.Enum("substring", "word", "regex", name="match_mode"), nullable=False
        ),
        sa.Column(
            "target_fields",
            sa.ARRAY(sa.String(length=50)),
            server_default=sa.text("ARRAY['title', 'description']::varchar[]"),
            nullable=False,
        ),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("term"),
    )
    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("access_token_enc", sa.Text(), nullable=False),
        sa.Column("refresh_token_enc", sa.Text(), nullable=True),
        sa.Column("access_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider"),
    )
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.Text(), nullable=False),
        sa.Column("auth", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("crawler_key", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "fetch_strategy",
            sa.Enum("api", "rss", "json", "html", "browser", name="fetch_strategy"),
            nullable=False,
        ),
        sa.Column("interval_minutes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rate_limit_per_min", sa.Integer(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.Enum("scheduled", "manual", name="crawl_trigger"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "success", "partial", "failed", "skipped", name="crawl_status"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("items_fetched", sa.Integer(), nullable=False),
        sa.Column("items_new", sa.Integer(), nullable=False),
        sa.Column("items_updated", sa.Integer(), nullable=False),
        sa.Column("error_type", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "http_status_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_postings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("employment_type", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id", name="uq_job_postings_source_external_id"),
        sa.UniqueConstraint("source_id", "fingerprint", name="uq_job_postings_source_fingerprint"),
    )
    op.create_index(
        "ix_job_postings_deadline_at_open",
        "job_postings",
        ["deadline_at"],
        unique=False,
        postgresql_where=sa.text("is_open"),
    )
    op.create_index(
        "ix_job_postings_first_seen_at_open",
        "job_postings",
        [sa.literal_column("first_seen_at DESC")],
        unique=False,
        postgresql_where=sa.text("is_open"),
    )
    op.create_index(
        "ix_job_postings_source_first_seen_at",
        "job_postings",
        ["source_id", sa.literal_column("first_seen_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_job_postings_title_trgm",
        "job_postings",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_table(
        "job_keyword_matches",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("job_posting_id", sa.BigInteger(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.Column("matched_field", sa.String(length=50), nullable=False),
        sa.Column("matched_snippet", sa.Text(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_posting_id"], ["job_postings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["keyword_id"], ["keywords.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_posting_id", "keyword_id", name="uq_job_keyword_matches_posting_keyword"
        ),
    )
    op.create_table(
        "job_posting_revisions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("job_posting_id", sa.BigInteger(), nullable=False),
        sa.Column("changed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("old_content_hash", sa.String(length=64), nullable=False),
        sa.Column("new_content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_posting_id"], ["job_postings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("job_posting_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "channel", sa.Enum("kakao", "web_push", name="notification_channel"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "sending", "sent", "failed", name="notification_status"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["job_posting_id"], ["job_postings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_posting_id", "channel", name="uq_notifications_posting_channel"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """스키마를 이전 리비전으로 되돌린다."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notifications")
    op.drop_table("job_posting_revisions")
    op.drop_table("job_keyword_matches")
    op.drop_index(
        "ix_job_postings_title_trgm",
        table_name="job_postings",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index("ix_job_postings_source_first_seen_at", table_name="job_postings")
    op.drop_index(
        "ix_job_postings_first_seen_at_open",
        table_name="job_postings",
        postgresql_where=sa.text("is_open"),
    )
    op.drop_index(
        "ix_job_postings_deadline_at_open",
        table_name="job_postings",
        postgresql_where=sa.text("is_open"),
    )
    op.drop_table("job_postings")
    op.drop_table("crawl_runs")
    op.drop_table("sources")
    op.drop_table("push_subscriptions")
    op.drop_table("oauth_tokens")
    op.drop_table("keywords")
    op.drop_table("app_settings")
    op.execute("DROP TYPE IF EXISTS notification_status")
    op.execute("DROP TYPE IF EXISTS notification_channel")
    op.execute("DROP TYPE IF EXISTS crawl_status")
    op.execute("DROP TYPE IF EXISTS crawl_trigger")
    op.execute("DROP TYPE IF EXISTS fetch_strategy")
    op.execute("DROP TYPE IF EXISTS match_mode")
    op.execute("DROP TYPE IF EXISTS keyword_kind")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    # ### end Alembic commands ###
